language: ruby

env:
  - db: localhost

services:
  - elasticsearch
  - postgresql

addons:
  hosts:
      - db

before_script:
  - sleep 10

script:
  - bundle exec rake test
  - bundle exec rake db:create
  - bundle exec rspec
    