version: '3.6'
services:
  webserver:
    image: nginx
    ports:
      - "80:80"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_USER: myapp
  web:
    build: 
      context: .
      args:
        MASTERKEY: ${MASTERKEY}
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: puma
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
      MYAPP_DATABASE_PASSWORD: ${PASSWORD}
