version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
  dbbackup:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      MAILER_URL: ${MAILER_URL}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      TWITTER_API_CONSUMER_SECRET: ${TWITTER_API_CONSUMER_SECRET}
      TWITTER_API_ACESS_TOKEN_SECRET: ${TWITTER_API_ACESS_TOKEN_SECRET} 
      VIGILANCE_EMAIL: ${VIGILANCE_EMAIL}
      CSV_DATA_KEY: ${CSV_DATA_KEY}
